import { ArrowLeft, Banknote, CircleDollarSign, MoreHorizontal, Plus, RefreshCw, TrendingDown, TrendingUp } from "lucide-react"
import { useState } from "react"
import { Link, Navigate, useNavigate, useParams } from "react-router-dom"

import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { AccountLifecycleActions } from "@/features/accounts/account-lifecycle-actions"
import { useProfile } from "@/features/auth/profile-service"
import {
  CashEventDialog, FxDialog, HoldingDialog, PricesDialog, TradeDialog,
} from "@/features/investments/investment-action-dialogs"
import { useDetailedInvestment } from "@/features/investments/investments-hooks"
import type { DetailedCashEvent, DetailedTrade } from "@/features/investments/investment-types"
import { formatCurrency, formatSignedCurrency } from "@/lib/currency"
import { formatShortDate, getDateInputInTimeZone } from "@/lib/dates"
import { cn } from "@/lib/utils"

type DialogName = "buy" | "sell" | "prices" | "fx" | "holding" | "dividend" | "adjustment" | null

export function InvestmentAccountPage() {
  const { accountId } = useParams()
  const navigate = useNavigate()
  const query = useDetailedInvestment(accountId)
  const profile = useProfile()
  const [dialog, setDialog] = useState<DialogName>(null)
  if (query.isLoading || profile.isLoading) return <Skeleton className="h-[40rem] rounded-3xl" />
  if (query.isError || !query.data || !accountId) return <Navigate to="/investments" replace />
  const data = query.data; const { account, value, holdings, trades, cash_events: events } = data
  const baseCurrency = profile.data?.base_currency ?? "SGD"
  const today = getDateInputInTimeZone(profile.data?.timezone ?? "Asia/Singapore")
  const activeHoldings = holdings.filter((holding) => !holding.archived_at)
  const archived = Boolean(account.archived_at)
  const representedTotal = Math.max(value.native_value_minor ?? 0, 0)
  const cashAllocation = representedTotal > 0 ? value.broker_cash_minor / representedTotal * 100 : 0
  const holdingsAllocation = representedTotal > 0 ? value.holdings_value_minor / representedTotal * 100 : 0
  const totalMarket = Math.max(value.holdings_value_minor, 0)

  return <div className="space-y-7">
    <header className="flex items-center gap-3"><Button variant="ghost" size="icon" aria-label="Back to investments" render={<Link to="/investments" />}><ArrowLeft /></Button><div className="min-w-0"><p className="eyebrow">Detailed portfolio</p><h1 className="truncate text-2xl font-semibold">{account.name}</h1><p className="mt-1 text-xs text-muted-foreground">{account.institution ?? "Investment account"} · {account.currency_code}</p></div></header>
    <section className="rounded-[1.75rem] bg-card/65 px-5 py-6 ring-1 ring-white/5 sm:px-7"><p className="section-heading">Account value</p><p className="mt-3 text-[clamp(2rem,10vw,3.5rem)] font-semibold tracking-[-0.05em] tabular-nums">{value.native_value_minor === null ? "Price needed" : formatCurrency(value.native_value_minor, account.currency_code)}</p>{value.base_value_available && value.base_value_minor !== null && account.currency_code !== baseCurrency && <p className="mt-2 text-sm text-muted-foreground">{formatCurrency(value.base_value_minor, baseCurrency)} base value</p>}{!value.base_value_available && <button className="mt-3 text-left text-sm text-amber-200 underline-offset-4 hover:underline" onClick={() => setDialog(value.missing_price_count > 0 ? "prices" : "fx")}>Base value unavailable · add {value.missing_price_count > 0 ? "missing prices" : `${account.currency_code} → ${baseCurrency} FX`}</button>}
      <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Broker cash" value={formatCurrency(value.broker_cash_minor, account.currency_code)} /><Metric label="Holdings" value={formatCurrency(value.holdings_value_minor, account.currency_code)} /><Metric label="Unrealised" value={value.unrealized_gain_minor === null ? "Price needed" : formatSignedCurrency(value.unrealized_gain_minor, account.currency_code)} tone={value.unrealized_gain_minor ?? undefined} /><Metric label="Realised" value={formatSignedCurrency(value.realized_gain_minor, account.currency_code)} tone={value.realized_gain_minor} /></div>
    </section>
    {archived && <section className="rounded-2xl bg-secondary/40 px-4 py-3 text-sm text-muted-foreground ring-1 ring-white/5"><strong className="text-foreground">Archived account.</strong> Its investment history remains readable, but new portfolio activity is disabled until it is restored.</section>}
    {!archived && <div className="grid grid-cols-2 gap-2 sm:flex"><Button onClick={() => setDialog("buy")}><TrendingUp /> Buy</Button><Button variant="outline" onClick={() => setDialog("sell")}><TrendingDown /> Sell</Button><Button variant="outline" onClick={() => setDialog("prices")}><RefreshCw /> Update prices</Button><Button variant="outline" onClick={() => setDialog("holding")}><Plus /> Holding</Button></div>}
    <section className="rounded-2xl bg-card/45 p-4"><h2 className="section-heading">Portfolio allocation</h2><div className="mt-3 space-y-3 text-sm"><AllocationRow label="Broker cash" percentage={cashAllocation} /><AllocationRow label="Holdings" percentage={holdingsAllocation} /></div><div className="mt-3 flex flex-wrap gap-1">{activeHoldings.map((holding)=><Button key={holding.id} size="sm" variant="ghost" render={<Link to={`/investments/${accountId}/holdings/${holding.id}`} />}>View {holding.symbol}</Button>)}</div></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="section-heading">Holdings</h2><p className="text-xs text-muted-foreground">Updated {value.latest_price_date ? formatShortDate(value.latest_price_date) : "—"}</p></div>{activeHoldings.length === 0 ? <div className="rounded-2xl bg-card/55 px-5 py-8 text-center text-sm text-muted-foreground">No active holdings. Add one, then record a buy.</div> : <div className="overflow-hidden rounded-2xl bg-card/65 ring-1 ring-white/5">{activeHoldings.map((holding,index)=>{const market=holding.market_value_minor;const allocation=totalMarket>0&&market!==null?market/totalMarket*100:0;const gain=holding.unrealized_gain_minor;return <article key={holding.id} className={cn("px-4 py-4 sm:px-5",index>0&&"border-t border-border/25")}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h3 className="font-semibold">{holding.symbol}</h3><p className="truncate text-xs text-muted-foreground">{holding.name} · {formatQuantity(holding.quantity)} shares</p></div><div className="shrink-0 text-right"><p className="font-semibold tabular-nums">{market===null?"Price needed":formatCurrency(market,account.currency_code)}</p>{gain!==null&&<p className={cn("text-xs",gain>=0?"text-emerald-300":"text-destructive")}>{formatSignedCurrency(gain,account.currency_code)}</p>}</div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(Math.max(allocation,0),100)}%`}} /></div><div className="mt-2 flex justify-between text-[0.68rem] text-muted-foreground"><span>Cost {formatCurrency(holding.cost_basis_minor,account.currency_code)}</span><span>{allocation.toFixed(1)}% of holdings</span></div></article>})}</div>}</section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="section-heading">Investment activity</h2>{!archived && <Button size="sm" variant="ghost" onClick={()=>setDialog("dividend")}><CircleDollarSign /> Dividend</Button>}</div><div className="overflow-hidden rounded-2xl bg-card/55 ring-1 ring-white/5">{mergeActivity(trades,events).slice(0,12).map((item,index)=><ActivityRow key={`${item.kind}-${item.id}`} item={item} currency={account.currency_code} bordered={index>0} holdings={holdings}/>) }{trades.length+events.length===0&&<p className="px-5 py-8 text-center text-sm text-muted-foreground">No investment activity yet.</p>}</div></section>
    {!archived && <section className="rounded-2xl bg-secondary/35 p-4"><div className="flex items-center gap-2"><MoreHorizontal className="size-4 text-primary"/><h2 className="text-sm font-semibold">Reconciliation and valuation</h2></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDialog("adjustment")}><Banknote /> Adjust broker cash</Button>{account.currency_code!==baseCurrency&&<Button size="sm" variant="outline" onClick={()=>setDialog("fx")}>Update manual FX</Button>}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">Cash adjustments require a reason and should not replace normal transfers. Manual FX changes valuation only.</p></section>}
    <section className="rounded-2xl bg-card/35 p-4 ring-1 ring-white/5"><h2 className="section-heading">Account lifecycle</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Archive preserves this history and requires a zero represented value. Permanent deletion is only for mistaken or test accounts without active transaction references.</p><AccountLifecycleActions className="mt-3" archived={archived} baseCurrency={baseCurrency} account={{id:account.id,name:account.name,account_type:"investment",currency_code:account.currency_code,investment_tracking_mode:"detailed",native_value_minor:value.native_value_minor,base_value_minor:value.base_value_minor}} onDeleted={()=>navigate("/accounts",{replace:true})} /></section>
    {dialog==="buy"&&<TradeDialog accountId={accountId} currencyCode={account.currency_code} today={today} holdings={activeHoldings} type="buy" open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="sell"&&<TradeDialog accountId={accountId} currencyCode={account.currency_code} today={today} holdings={activeHoldings} type="sell" open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="prices"&&<PricesDialog accountId={accountId} currencyCode={account.currency_code} today={today} holdings={activeHoldings} open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="holding"&&<HoldingDialog accountId={accountId} open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="dividend"&&<CashEventDialog accountId={accountId} currencyCode={account.currency_code} today={today} holdings={activeHoldings} type="dividend" open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="adjustment"&&<CashEventDialog accountId={accountId} currencyCode={account.currency_code} today={today} holdings={activeHoldings} type="cash_adjustment" open onOpenChange={(open)=>!open&&setDialog(null)} />}{dialog==="fx"&&account.currency_code!==baseCurrency&&<FxDialog fromCurrency={account.currency_code} baseCurrency={baseCurrency} today={today} open onOpenChange={(open)=>!open&&setDialog(null)} />}
  </div>
}

function Metric({label,value,tone}:{label:string;value:string;tone?:number}){return <div className="min-w-0 rounded-xl bg-secondary/45 p-3"><p className="text-[0.68rem] uppercase tracking-wider text-muted-foreground">{label}</p><p className={cn("mt-1 truncate text-sm font-semibold tabular-nums",tone!==undefined&&(tone>=0?"text-emerald-300":"text-destructive"))}>{value}</p></div>}
function AllocationRow({label,percentage}:{label:string;percentage:number}){const safe=Math.min(Math.max(percentage,0),100);return <div><div className="flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="tabular-nums">{percentage.toFixed(1)}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${safe}%`}} /></div></div>}
type Activity = ({kind:"trade"}&DetailedTrade)|({kind:"event"}&DetailedCashEvent)
function mergeActivity(trades:DetailedTrade[],events:DetailedCashEvent[]):Activity[]{return [...trades.map((item)=>({...item,kind:"trade" as const})),...events.map((item)=>({...item,kind:"event" as const}))].sort((a,b)=>{const ad=a.kind==="trade"?a.trade_date:a.event_date;const bd=b.kind==="trade"?b.trade_date:b.event_date;return bd.localeCompare(ad)||(b.created_at.localeCompare(a.created_at))})}
function ActivityRow({item,currency,bordered,holdings}:{item:Activity;currency:string;bordered:boolean;holdings:Array<{id:string;symbol:string}>}){const holdingId=item.holding_id;const symbol=holdings.find((holding)=>holding.id===holdingId)?.symbol;const date=item.kind==="trade"?item.trade_date:item.event_date;const title=item.kind==="trade"?item.trade_type==="opening_position"?"Opening position":`${item.trade_type==="buy"?"Buy":"Sell"} ${symbol??"holding"}`:item.event_type==="opening_cash"?"Opening broker cash":item.event_type==="dividend"?`Dividend · ${symbol??"holding"}`:"Broker cash adjustment";const amount=item.kind==="trade"?item.cash_effect_minor:item.amount_minor;return <div className={cn("flex items-center justify-between gap-4 px-4 py-3",bordered&&"border-t border-border/25")}><div className="min-w-0"><p className="truncate text-sm font-medium">{title}</p><p className="truncate text-xs text-muted-foreground">{item.note||formatShortDate(date)} · {formatShortDate(date)}</p></div><p className={cn("shrink-0 text-sm font-semibold tabular-nums",amount>0?"text-emerald-300":amount<0?"text-destructive":"text-muted-foreground")}>{formatSignedCurrency(amount,currency)}</p></div>}
function formatQuantity(value:number){return new Intl.NumberFormat("en-SG",{maximumFractionDigits:10}).format(value)}
